### PR TITLE
Fix Qt6 build failure on QDomDocument::ParseResult conversion error

### PR DESCRIPTION
**Pull request by cjmayo**
```
src/model/modelbase.cpp: In member function ‘ModelPart* ModelBase::createOldSchematicPartAux(ModelPart*, const QString&, const QString&, const QString&)’: src/model/modelbase.cpp:847:36: error: cannot convert ‘QDomDocument::ParseResult’ to ‘bool’ in initialization
  847 |         bool ok = oldDoc.setContent(&newFzp);
      |                   ~~~~~~~~~~~~~~~~~^~~~~~~~~
      |                                    |
      |                                    QDomDocument::ParseResult
```

Ensure Qt6 uses the deprecated:
bool QDomDocument::setContent(const QByteArray &buffer, QString *errorMsg, int *errorLine = nullptr, int *errorColumn = nullptr)

which in Qt5 is:
bool QDomDocument::setContent(const QByteArray &buffer, QString *errorMsg = nullptr, int *errorLine = nullptr, int *errorColumn = nullptr)

### CODE REVIEW

**Comment by DanielBarie** [comment]
I just did a succesful build with Qt6.6.1. A ton of deprecation warnings but no build failure.

**Comment by cjmayo** [comment]
Yes, the code was updated: bd010ce4961bd90505fa540032dfcc97500e364c.
