### ISSUE TITLE
Won't compile on OS X 10.7.4: redefinition of 'viewLayerIDs' with a different type

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2075]
_From [elija...@mac.com](https://code.google.com/u/100346973317850103324/) on June 29, 2012 16:33:35_

I'm unable to compile the latest revision of Fritzing on the Mac (10.7.4). When on the debug config, I get an error:
../fritzing/src/mainwindow_export.cpp:419:12: error: redefinition of 'viewLayerIDs' with a different type. It seems revision 6114 broke something. I get a similar error on the release version.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2075_
