### ISSUE TITLE
r6398 won't compile on Mountain Lion

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2206]
_From [elija...@mac.com](https://code.google.com/u/100346973317850103324/) on September 10, 2012 10:27:15_

Fritzing won't compile on Mountain Lion, with QT 4.8.1. Here're the two errors:

../fritzing/src/mainwindow/mainwindow.cpp:2510:77: error: use of undeclared identifier 'prefix'; did you mean 'profil'?
                platformDependantStylePath = QString(":/resources/styles/mac-&#37;1.qss").arg(prefix);

../fritzing/src/mainwindow/mainwindow.cpp:2510:73: error: no matching member function for call to 'arg'
                platformDependantStylePath = QString(":/resources/styles/mac-&#37;1.qss").arg(prefix);

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2206_
